using System;
using System.Collections.Generic;
using System.IO;
using QwkNet.Archive;
using QwkNet.Archive.Zip;
using QwkNet.Core;
using QwkNet.Encoding;
using QwkNet.Models.Control;
using QwkNet.Models.Indexing;
using QwkNet.Models.Messages;
using QwkNet.Parsing;

namespace QwkNet;

/// <summary>
/// Represents a REP (reply) packet for upload back to the BBS.
/// </summary>
/// <remarks>
/// <para>
/// REP packets contain user replies to be uploaded to the BBS. The format
/// is similar to QWK packets but contains only messages and their indexes.
/// </para>
/// <para>
/// This class provides deterministic output: given the same messages and
/// control data, the generated bytes will be identical across builds.
/// </para>
/// </remarks>
public sealed class RepPacket : IDisposable
{
  private const int QwkRecordSize = 128;
  private readonly string _bbsId;
  private readonly List<Message> _messages;
  private readonly Dictionary<ushort, List<Message>> _messagesByConference;
  private bool _disposed;

  /// <summary>
  /// Gets the BBS identifier for this REP packet.
  /// </summary>
  /// <remarks>
  /// Always uppercase. Used to name the message payload within the archive
  /// (e.g., <c>MYBBS.MSG</c>), the outer REP file (e.g., <c>MYBBS.REP</c>),
  /// and appears in the first line of CONTROL.DAT.
  /// </remarks>
  public string BbsId => _bbsId;

  /// <summary>
  /// Gets the read-only collection of messages in this REP packet.
  /// </summary>
  public IReadOnlyList<Message> Messages => _messages;

  /// <summary>
  /// Initialises a new instance of the <see cref="RepPacket"/> class.
  /// </summary>
  /// <param name="bbsId">
  /// The BBS identifier (1-8 characters). Normalised to uppercase on construction
  /// (e.g. <c>"dmine"</c> is stored as <c>"DMINE"</c>). Allowed characters are
  /// ASCII letters A-Z (case-insensitive) and digits 0-9.
  /// </param>
  /// <exception cref="ArgumentNullException">
  /// Thrown when <paramref name="bbsId"/> is <see langword="null"/>.
  /// </exception>
  /// <exception cref="ArgumentException">
  /// Thrown when <paramref name="bbsId"/> is empty, whitespace, exceeds 8 characters,
  /// or contains characters other than ASCII letters and digits.
  /// </exception>
  private RepPacket(string bbsId)
  {
    if (bbsId == null)
    {
      throw new ArgumentNullException(nameof(bbsId));
    }

    if (string.IsNullOrWhiteSpace(bbsId))
    {
      throw new ArgumentException("BBS ID cannot be empty or whitespace.", nameof(bbsId));
    }

    // Normalise to uppercase so callers can pass "dmine" and get "DMINE".
    string normalizedId = bbsId.ToUpperInvariant();

    if (normalizedId.Length > 8)
    {
      throw new ArgumentException("BBS ID cannot exceed 8 characters.", nameof(bbsId));
    }

    foreach (char c in normalizedId)
    {
      if ((c < 'A' || c > 'Z') && (c < '0' || c > '9'))
      {
        throw new ArgumentException(
          "BBS ID may only contain ASCII letters (A-Z) and digits (0-9).", nameof(bbsId));
      }
    }

    _bbsId = normalizedId;
    _messages = new List<Message>();
    _messagesByConference = new Dictionary<ushort, List<Message>>();
    _disposed = false;
  }

  /// <summary>
  /// Creates a new REP packet using control data from a QWK packet.
  /// </summary>
  /// <param name="control">
  /// The control data from the original QWK packet.
  /// </param>
  /// <returns>
  /// A new <see cref="RepPacket"/> instance ready to receive messages.
  /// </returns>
  /// <exception cref="ArgumentNullException">
  /// Thrown when <paramref name="control"/> is <see langword="null"/>.
  /// </exception>
  public static RepPacket Create(ControlDat control)
  {
    if (control == null)
    {
      throw new ArgumentNullException(nameof(control));
    }

    return new RepPacket(control.BbsId);
  }

  /// <summary>
  /// Creates a new REP packet with a specific BBS identifier.
  /// </summary>
  /// <param name="bbsId">
  /// The BBS identifier (1-8 characters, typically uppercase).
  /// </param>
  /// <returns>
  /// A new <see cref="RepPacket"/> instance ready to receive messages.
  /// </returns>
  /// <exception cref="ArgumentNullException">
  /// Thrown when <paramref name="bbsId"/> is <see langword="null"/>.
  /// </exception>
  /// <exception cref="ArgumentException">
  /// Thrown when <paramref name="bbsId"/> is invalid.
  /// </exception>
  public static RepPacket Create(string bbsId)
  {
    return new RepPacket(bbsId);
  }

  /// <summary>
  /// Adds a message to the REP packet.
  /// </summary>
  /// <param name="message">
  /// The message to add.
  /// </param>
  /// <exception cref="ArgumentNullException">
  /// Thrown when <paramref name="message"/> is <see langword="null"/>.
  /// </exception>
  /// <exception cref="ObjectDisposedException">
  /// Thrown when this instance has been disposed.
  /// </exception>
  /// <remarks>
  /// Messages are added in the order they are provided. The ASCII message number
  /// field (offsets 1–7) is set to the conference number during packet generation,
  /// per the REP packet specification.
  /// </remarks>
  public void AddMessage(Message message)
  {
    ObjectDisposedException.ThrowIf(_disposed, this);

    if (message == null)
    {
      throw new ArgumentNullException(nameof(message));
    }

    _messages.Add(message);

    // Track messages by conference for index generation.
    if (!_messagesByConference.ContainsKey(message.ConferenceNumber))
    {
      _messagesByConference[message.ConferenceNumber] = new List<Message>();
    }

    _messagesByConference[message.ConferenceNumber].Add(message);
  }

  /// <summary>
  /// Saves the REP packet to a stream.
  /// </summary>
  /// <param name="output">
  /// The stream to write the REP packet to.
  /// </param>
  /// <exception cref="ArgumentNullException">
  /// Thrown when <paramref name="output"/> is <see langword="null"/>.
  /// </exception>
  /// <exception cref="ArgumentException">
  /// Thrown when <paramref name="output"/> is not writable.
  /// </exception>
  /// <exception cref="ObjectDisposedException">
  /// Thrown when this instance has been disposed.
  /// </exception>
  /// <remarks>
  /// This method generates a complete REP packet as a ZIP archive containing:
  /// <list type="bullet">
  /// <item><description>CONTROL.DAT - BBS identifier line</description></item>
  /// <item><description>BBSID.MSG - All messages with proper padding (e.g., <c>DMINE.MSG</c>)</description></item>
  /// <item><description>N.NDX files - Index files for each conference</description></item>
  /// </list>
  /// </remarks>
  public void Save(Stream output)
  {
    ObjectDisposedException.ThrowIf(_disposed, this);

    if (output == null)
    {
      throw new ArgumentNullException(nameof(output));
    }

    if (!output.CanWrite)
    {
      throw new ArgumentException("Stream must be writable.", nameof(output));
    }

    using (IArchiveWriter writer = new ZipArchiveWriter())
    {
      // Generate CONTROL.DAT.
      using (Stream controlStream = GenerateControlDat())
      {
        writer.AddFile("CONTROL.DAT", controlStream);
      }

      // Generate BBSID.MSG — BBS servers identify the reply payload by this
      // name; a generic MESSAGES.DAT would be silently dropped by most servers.
      using (Stream messagesStream = GenerateMessagesDat())
      {
        writer.AddFile($"{_bbsId}.MSG", messagesStream);
      }

      // Generate index files for each conference.
      Dictionary<int, IndexFile> indexes = GenerateIndexes();
      foreach (KeyValuePair<int, IndexFile> kvp in indexes)
      {
        int conferenceNumber = kvp.Key;
        IndexFile indexFile = kvp.Value;

        string indexFileName = $"{conferenceNumber}.NDX";

        using (MemoryStream indexStream = new MemoryStream())
        {
          MessageIndexer.WriteIndex(indexFile, indexStream);
          indexStream.Position = 0;
          writer.AddFile(indexFileName, indexStream);
        }
      }

      // Write the ZIP archive to the output stream.
      writer.Save(output);
    }
  }

  /// <summary>
  /// Saves the REP packet to a file.
  /// </summary>
  /// <param name="filePath">
  /// The path to write the REP packet to.
  /// </param>
  /// <exception cref="ArgumentNullException">
  /// Thrown when <paramref name="filePath"/> is <see langword="null"/>.
  /// </exception>
  /// <exception cref="ObjectDisposedException">
  /// Thrown when this instance has been disposed.
  /// </exception>
  public void SaveToFile(string filePath)
  {
    ObjectDisposedException.ThrowIf(_disposed, this);

    if (filePath == null)
    {
      throw new ArgumentNullException(nameof(filePath));
    }

    using (FileStream fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
    {
      Save(fs);
    }
  }

  /// <summary>
  /// Generates the CONTROL.DAT file content.
  /// </summary>
  /// <returns>
  /// A <see cref="MemoryStream"/> containing the CONTROL.DAT data.
  /// </returns>
  /// <remarks>
  /// For REP packets, CONTROL.DAT contains only the BBS ID on the first line.
  /// This is the minimal valid CONTROL.DAT for a reply packet.
  /// </remarks>
  private Stream GenerateControlDat()
  {
    MemoryStream stream = new MemoryStream();
    StreamWriter writer = new StreamWriter(stream, Cp437Encoding.GetEncoding(), leaveOpen: true);

    // REP CONTROL.DAT format: BBS ID on first line only.
    writer.WriteLine(_bbsId);
    writer.Flush();

    stream.Position = 0;
    return stream;
  }

  /// <summary>
  /// Generates the MESSAGES.DAT file content.
  /// </summary>
  /// <returns>
  /// A <see cref="MemoryStream"/> containing the MESSAGES.DAT data.
  /// </returns>
  /// <remarks>
  /// <para>
  /// MESSAGES.DAT consists of a header record followed by message records.
  /// Each message consists of a 128-byte header followed by N 128-byte blocks
  /// of body text, padded with spaces to fill the last block.
  /// </para>
  /// <para>
  /// The first record (header) contains the BBS ID, space-padded to 128 bytes.
  /// </para>
  /// <para>
  /// Per the REP packet specification, the ASCII message number field (offsets
  /// 1–7) of each message header contains the conference number, not a
  /// sequential index. The binary conference number at offsets 123–124 holds
  /// the same value. Both fields are set here during serialisation.
  /// </para>
  /// </remarks>
  private Stream GenerateMessagesDat()
  {
    MemoryStream stream = new MemoryStream();

    // Write MESSAGES.DAT header record (BBS ID, space-padded).
    WriteMessagesHeader(stream);

    // Write each message. Per the REP spec the message number field (offsets
    // 1–7) must contain the conference number, not a sequential counter.
    // Source: https://wmcbrine.com/mmail/specs/qwklay.html section 4.2.
    int recordOffset = 1; // Start at record 1 (after header block).

    foreach (Message message in _messages)
    {
      int conferenceNumber = message.ConferenceNumber;
      recordOffset = WriteMessage(stream, message, conferenceNumber, recordOffset);
    }

    stream.Position = 0;
    return stream;
  }

  /// <summary>
  /// Writes the MESSAGES.DAT header record.
  /// </summary>
  /// <param name="stream">
  /// The stream to write to.
  /// </param>
  /// <remarks>
  /// The header record is a 128-byte block containing the BBS ID at the start,
  /// with the remainder space-padded.
  /// </remarks>
  private void WriteMessagesHeader(Stream stream)
  {
    byte[] headerRecord = new byte[QwkRecordSize];

    // Fill with spaces.
    for (int i = 0; i < headerRecord.Length; i++)
    {
      headerRecord[i] = (byte)' ';
    }

    // Write BBS ID at the start using CP437 encoding.
    byte[] bbsIdBytes = Cp437Encoding.Encode(_bbsId);
    int copyLength = Math.Min(bbsIdBytes.Length, headerRecord.Length);
    Array.Copy(bbsIdBytes, 0, headerRecord, 0, copyLength);

    stream.Write(headerRecord, 0, headerRecord.Length);
  }

  /// <summary>
  /// Writes a single message to MESSAGES.DAT.
  /// </summary>
  /// <param name="stream">
  /// The stream to write to.
  /// </param>
  /// <param name="message">
  /// The message to write.
  /// </param>
  /// <param name="messageNumber">
  /// The value to write into the ASCII message number field (offsets 1–7).
  /// For REP packets this is always the conference number.
  /// </param>
  /// <param name="recordOffset">
  /// The current record offset in MESSAGES.DAT.
  /// </param>
  /// <returns>
  /// The updated record offset after writing this message.
  /// </returns>
  private int WriteMessage(Stream stream, Message message, int messageNumber, int recordOffset)
  {
    // Build the message header with the correct message number and block count.
    byte[] headerBytes = BuildMessageHeader(message, messageNumber);

    // Get the message body text encoded for QWK format (lines joined with
    // 0xE3 soft-CR terminators).
    string bodyText = message.Body.GetEncodedText();

    // Calculate block count (number of 128-byte blocks needed for the body).
    int bodyBlockCount = CalculateBlockCount(bodyText);

    // Per QWK specification, the block count field (offsets 116–121) holds
    // the total number of 128-byte blocks INCLUDING the header block itself.
    int totalBlockCount = bodyBlockCount + 1;
    WriteBlockCount(headerBytes, totalBlockCount);

    // Write message header then body blocks.
    stream.Write(headerBytes, 0, headerBytes.Length);
    recordOffset++;

    WriteMessageBody(stream, bodyText, bodyBlockCount);
    recordOffset += bodyBlockCount;

    return recordOffset;
  }

  /// <summary>
  /// Builds a 128-byte message header array.
  /// </summary>
  /// <param name="message">
  /// The message to build a header for.
  /// </param>
  /// <param name="messageNumber">
  /// The value to write into the ASCII message number field (offsets 1–7).
  /// For REP packets this is the conference number.
  /// </param>
  /// <returns>
  /// A 128-byte array containing the message header.
  /// </returns>
  /// <remarks>
  /// The raw header bytes from the message model are used as a base so that
  /// any fields not explicitly modelled are preserved. The status byte (offset 0)
  /// and message number field (offsets 1–7) are always recalculated from the
  /// message model to ensure they are consistent and correct for the REP format.
  /// </remarks>
  private static byte[] BuildMessageHeader(Message message, int messageNumber)
  {
    byte[] headerBytes = new byte[QwkRecordSize];

    // Use the raw header as a base to preserve fields not modelled explicitly.
    byte[] rawHeaderBytes = message.RawHeader.RawHeader;
    Array.Copy(rawHeaderBytes, 0, headerBytes, 0, QwkRecordSize);

    // Recalculate status byte (offset 0) from the message model — the raw
    // header may be stale if Status has been modified since parsing.
    headerBytes[0] = ConvertStatusToQwkByte(message.Status);

    // Write the message number field (offsets 1–7), clearing it first.
    // For REP packets this field holds the conference number per the spec.
    for (int i = 1; i < 8; i++)
    {
      headerBytes[i] = (byte)' ';
    }

    WriteAsciiField(headerBytes, 1, messageNumber.ToString(), 7);

    return headerBytes;
  }

  /// <summary>
  /// Converts <see cref="MessageStatus"/> flags to the QWK status byte.
  /// </summary>
  /// <param name="status">The status flags to convert.</param>
  /// <returns>
  /// The QWK status byte, where bits 0–6 encode the ASCII status character and
  /// bit 7 is set if <see cref="MessageStatus.HasNetworkTagLine"/> is present.
  /// </returns>
  private static byte ConvertStatusToQwkByte(MessageStatus status)
  {
    bool isPrivate = status.HasFlag(MessageStatus.Private);
    bool isRead = status.HasFlag(MessageStatus.Read);
    bool isCommentToSysop = status.HasFlag(MessageStatus.CommentToSysop);
    bool isSenderPassword = status.HasFlag(MessageStatus.SenderPasswordProtected);
    bool isGroupPassword = status.HasFlag(MessageStatus.GroupPasswordProtected);
    bool isGroupPasswordToAll = status.HasFlag(MessageStatus.GroupPasswordProtectedToAll);
    bool hasNetworkTagLine = status.HasFlag(MessageStatus.HasNetworkTagLine);

    // Resolve the ASCII status character, highest-priority class first.
    byte Resolve()
    {
      if (isGroupPasswordToAll) return (byte)'$';
      if (isGroupPassword)      return (byte)(isRead ? '#' : '!');
      if (isSenderPassword)     return (byte)(isRead ? '^' : '%');
      if (isCommentToSysop)     return (byte)(isRead ? '`' : '~');
      if (isPrivate)            return (byte)(isRead ? '+' : '*');
                                return (byte)(isRead ? '-' : ' ');
    }

    // Set bit 7 if the network tag-line flag is present.
    byte statusByte = Resolve();
    if (hasNetworkTagLine)
    {
      statusByte |= 0x80;
    }

    return statusByte;
  }

  /// <summary>
  /// Writes an ASCII field into a header byte array.
  /// </summary>
  /// <param name="headerBytes">
  /// The header byte array to write into.
  /// </param>
  /// <param name="offset">
  /// The starting offset within <paramref name="headerBytes"/> (0-based).
  /// </param>
  /// <param name="value">
  /// The string value to write.
  /// </param>
  /// <param name="maxLength">
  /// The maximum number of bytes to write.
  /// </param>
  private static void WriteAsciiField(byte[] headerBytes, int offset, string value, int maxLength)
  {
    if (string.IsNullOrEmpty(value))
    {
      return;
    }

    string truncated = value.Length > maxLength ? value.Substring(0, maxLength) : value;

    byte[] valueBytes = Cp437Encoding.Encode(truncated);
    Array.Copy(valueBytes, 0, headerBytes, offset, valueBytes.Length);
  }

  /// <summary>
  /// Calculates the number of 128-byte blocks needed for a message body.
  /// </summary>
  /// <param name="bodyText">
  /// The message body text.
  /// </param>
  /// <returns>
  /// The number of 128-byte blocks required, minimum 1.
  /// </returns>
  private static int CalculateBlockCount(string bodyText)
  {
    if (string.IsNullOrEmpty(bodyText))
    {
      return 1;
    }

    byte[] encoded = Cp437Encoding.Encode(bodyText);
    int blockCount = (encoded.Length + QwkRecordSize - 1) / QwkRecordSize;

    return Math.Max(1, blockCount);
  }

  /// <summary>
  /// Writes the block count into the message header at offsets 116–121.
  /// </summary>
  /// <param name="headerBytes">
  /// The header byte array to write into.
  /// </param>
  /// <param name="blockCount">
  /// The total block count (header block + body blocks) to write.
  /// </param>
  private static void WriteBlockCount(byte[] headerBytes, int blockCount)
  {
    // Block count field: offsets 116–121 (6 bytes, ASCII, right-justified).
    string blockCountStr = blockCount.ToString().PadLeft(6);
    WriteAsciiField(headerBytes, 116, blockCountStr, 6);
  }

  /// <summary>
  /// Writes padded message body blocks to the stream.
  /// </summary>
  /// <param name="stream">
  /// The stream to write to.
  /// </param>
  /// <param name="bodyText">
  /// The message body text encoded with 0xE3 line terminators.
  /// </param>
  /// <param name="blockCount">
  /// The number of 128-byte blocks to write.
  /// </param>
  private static void WriteMessageBody(Stream stream, string bodyText, int blockCount)
  {
    byte[] bodyBytes = Cp437Encoding.Encode(bodyText ?? string.Empty);
    int totalSize = blockCount * QwkRecordSize;

    byte[] paddedBuffer = new byte[totalSize];

    // Fill with spaces, then overlay the body bytes.
    for (int i = 0; i < paddedBuffer.Length; i++)
    {
      paddedBuffer[i] = (byte)' ';
    }

    int copyLength = Math.Min(bodyBytes.Length, paddedBuffer.Length);
    Array.Copy(bodyBytes, 0, paddedBuffer, 0, copyLength);

    stream.Write(paddedBuffer, 0, paddedBuffer.Length);
  }

  /// <summary>
  /// Generates NDX index files for all conferences present in this REP packet.
  /// </summary>
  /// <returns>
  /// A dictionary mapping conference number to its <see cref="IndexFile"/>.
  /// </returns>
  /// <remarks>
  /// Each NDX entry is a 4-byte MSBIN float encoding the 128-byte record offset
  /// of the message header within MESSAGES.DAT (record 0 being the ID block).
  /// </remarks>
  private Dictionary<int, IndexFile> GenerateIndexes()
  {
    Dictionary<int, IndexFile> indexes = new Dictionary<int, IndexFile>();
    Dictionary<int, List<IndexEntry>> entriesByConference = new Dictionary<int, List<IndexEntry>>();

    // Start at record 1 — record 0 is the MESSAGES.DAT ID block.
    int globalRecordOffset = 1;

    foreach (Message message in _messages)
    {
      int conferenceNumber = message.ConferenceNumber;

      if (!entriesByConference.ContainsKey(conferenceNumber))
      {
        entriesByConference[conferenceNumber] = new List<IndexEntry>();
      }

      // Use GetEncodedText() for consistency with WriteMessage body encoding.
      int bodyBlockCount = CalculateBlockCount(message.Body.GetEncodedText());

      List<IndexEntry> entries = entriesByConference[conferenceNumber];

      int entryMessageNumber = entries.Count + 1;
      byte[] msbinBytes = MsbinConverter.FromDouble((double)globalRecordOffset);
      IndexEntry entry = new IndexEntry(entryMessageNumber, globalRecordOffset, msbinBytes);

      entries.Add(entry);

      // Advance past this message: 1 header block + N body blocks.
      globalRecordOffset += (1 + bodyBlockCount);
    }

    foreach (KeyValuePair<int, List<IndexEntry>> kvp in entriesByConference)
    {
      int conferenceNumber = kvp.Key;
      List<IndexEntry> entries = kvp.Value;

      IndexFile indexFile = new IndexFile(
        conferenceNumber,
        entries,
        isValid: true,
        validatedAgainstFileSize: 0);

      indexes[conferenceNumber] = indexFile;
    }

    return indexes;
  }

  /// <summary>
  /// Releases the resources used by this <see cref="RepPacket"/>.
  /// </summary>
  public void Dispose()
  {
    if (_disposed)
    {
      return;
    }

    _messages.Clear();
    _messagesByConference.Clear();
    _disposed = true;
  }
}